package main

import "fmt"

func printHelp() {
	h := headerStyle.Render
	c := connNameStyle.Render
	d := dimStyle.Render
	m := menuKeyStyle.Render
	w := connTargetStyle.Render

	fmt.Println()
	fmt.Println(renderLogo())
	fmt.Println()
	fmt.Println(h("  OVERVIEW"))
	fmt.Println()
	fmt.Println(w("  SecureWrapper is a credential vault and connection passthrough."))
	fmt.Println(w("  It stores encrypted connection profiles (SSH, API, SFTP, etc.)"))
	fmt.Println(w("  and lets automation tools execute authenticated commands without"))
	fmt.Println(w("  ever seeing the credentials."))
	fmt.Println()
	fmt.Println(w("  Particularly useful when paired with an LLM agent: the AI gets"))
	fmt.Println(w("  an auth key, not your secrets. It sees connection names and"))
	fmt.Println(w("  command output — never passwords, API keys, or SSH credentials."))
	fmt.Println(w("  If a transcript leaks, revoke the auth key or wipe the vault;"))
	fmt.Println(w("  the leaked conversation cannot reconstruct your credentials."))
	fmt.Println()
	fmt.Println(d("  The vault is encrypted with three factors:"))
	fmt.Println(d("    1. Your passphrase (or auth key)"))
	fmt.Println(d("    2. This machine's hardware fingerprint"))
	fmt.Println(d("    3. A unique key embedded in this binary"))
	fmt.Println()

	fmt.Println(h("  INTERACTIVE MODE"))
	fmt.Println()
	fmt.Println(w("  Run with no arguments to manage the vault:"))
	fmt.Println()
	fmt.Println(c("    ./wrapper"))
	fmt.Println()

	fmt.Println(h("  CONNECTION MODE"))
	fmt.Println()
	fmt.Println(w("  Three flags are required. Everything after is passthrough:"))
	fmt.Println()
	fmt.Println(c("    ./wrapper --sys <name> --<mode> [args...]"))
	fmt.Println()
	fmt.Println(d("  Auth key (one of these, in priority order):"))
	fmt.Println(c("    WRAPPER_AUTH_KEY=swk_xxx ./wrapper ...  ") + d("(preferred — not in ps)"))
	fmt.Println(c("    ./wrapper --key-file /path/to/keyfile ..."))
	fmt.Println(c("    ./wrapper --key swk_xxx ...             ") + d("(visible in ps aux)"))
	fmt.Println()

	fmt.Println(h("  MODES"))
	fmt.Println()
	fmt.Printf("  %s  %s\n", m("--ssh  "), w("Execute a command on a remote host"))
	fmt.Printf("  %s  %s\n", m("--scp  "), w("Copy files to/from a remote host"))
	fmt.Printf("  %s  %s\n", m("--sftp "), w("Interactive file transfer session"))
	fmt.Printf("  %s  %s\n", m("--rsync"), w("Sync files over SSH"))
	fmt.Printf("  %s  %s\n", m("--api  "), w("Make an HTTP API request"))
	fmt.Printf("  %s  %s\n", m("--db   "), w("Run a SQL query (Postgres / MySQL / SQL Server)"))
	fmt.Printf("  %s  %s\n", m("--winrm"), w("Run a PowerShell command via WinRM"))
	fmt.Printf("  %s  %s\n", m("--test "), w("Test connectivity (no command)"))
	fmt.Println()

	fmt.Println(h("  EXAMPLES"))
	fmt.Println()
	fmt.Println(d("  SSH — run a command:"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys myserver --ssh \"df -h\""))
	fmt.Println()
	fmt.Println(d("  SSH — interactive session:"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys myserver --ssh"))
	fmt.Println()
	fmt.Println(d("  SCP — copy file to remote:"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys myserver --scp file.txt :/remote/path/"))
	fmt.Println()
	fmt.Println(d("  SCP — copy file from remote:"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys myserver --scp :/remote/file.txt ./local/"))
	fmt.Println()
	fmt.Println(d("  SFTP — batch commands:"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys myserver --sftp \"get /remote/file.txt\""))
	fmt.Println()
	fmt.Println(d("  Rsync — sync directory:"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys myserver --rsync -av /local/dir/ :/remote/dir/"))
	fmt.Println()
	fmt.Println(d("  API — GET request:"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys myapi --api GET /endpoint"))
	fmt.Println()
	fmt.Println(d("  API — POST with body:"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys myapi --api POST /endpoint '{\"key\":\"value\"}'"))
	fmt.Println()
	fmt.Println(d("  Database — run a SELECT (TSV output with header):"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys mydb --db \"SELECT id, name FROM users LIMIT 10\""))
	fmt.Println()
	fmt.Println(d("  WinRM — run PowerShell:"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys mywinhost --winrm \"Get-Service wuauserv\""))
	fmt.Println()
	fmt.Println(d("  Test connectivity:"))
	fmt.Println(c("    ./wrapper --key swk_xxx --sys myserver --test"))
	fmt.Println()

	fmt.Println(h("  REMOTE PATHS"))
	fmt.Println()
	fmt.Println(w("  For SCP and Rsync, prefix remote paths with \":\" — the wrapper"))
	fmt.Println(w("  automatically prepends user@host from the connection profile."))
	fmt.Println()
	fmt.Println(d("    :/path/to/file  →  user@host:/path/to/file"))
	fmt.Println()

	fmt.Println(h("  AUTH KEYS"))
	fmt.Println()
	fmt.Println(w("  Auth keys allow automated tools to use connections without the"))
	fmt.Println(w("  vault passphrase. Each key is shown once at creation. Generate"))
	fmt.Println(w("  one key per calling system for individual revocation."))
	fmt.Println()
	fmt.Println(d("  Manage keys from the interactive menu: [K] Auth keys"))
	fmt.Println()

	fmt.Println(h("  SECURITY"))
	fmt.Println()
	fmt.Println(w("  • Vault encrypted AES-256-GCM with Argon2id key derivation"))
	fmt.Println(w("  • Bound to this machine — won't decrypt on different hardware"))
	fmt.Println(w("  • Bound to this binary — won't decrypt with a different build"))
	fmt.Println(w("  • Auth keys stored as hashes — plaintext never persisted"))
	fmt.Println(w("  • Passphrase policy: 12+ chars, upper+lower+digit+special, not common"))
	fmt.Println(w("  • 5 failed passphrase attempts silently wipes the vault"))
	fmt.Println(w("  • Local-only — remote calls are rejected"))
	fmt.Println()

	fmt.Println(h("  SSH TUNNELING"))
	fmt.Println()
	fmt.Println(w("  Any database or WinRM connection can be routed through a stored"))
	fmt.Println(w("  SSH connection (bastion / jumphost). Set the \"Tunnel via SSH\""))
	fmt.Println(w("  field on the target connection to the name of an SSH profile in"))
	fmt.Println(w("  the vault — the wrapper opens the SSH session, forwards a local"))
	fmt.Println(w("  port, and transparently connects through it."))
	fmt.Println()
	fmt.Println(d("  • DB drivers and WinRM clients stay unmodified"))
	fmt.Println(d("  • Inner SSL/TLS may need adjusting since traffic appears to come from 127.0.0.1"))
	fmt.Println()

	fmt.Println(h("  HARDWARE MIGRATION"))
	fmt.Println()
	fmt.Println(w("  Moving to a new machine (new CPU, new motherboard, new host)?"))
	fmt.Println(w("  Use Config → Export for Hardware Migration on the source machine."))
	fmt.Println(w("  The export file is encrypted with your passphrase plus a random"))
	fmt.Println(w("  one-time code shown on screen. Write down the code, copy the"))
	fmt.Println(w("  export file next to the new binary, and launch wrapper there —"))
	fmt.Println(w("  the import prompt appears automatically."))
	fmt.Println()
	fmt.Println(d("  • Expires 24 hours after export (network-time verified)"))
	fmt.Println(d("  • Cannot be re-imported — each export is single-use"))
	fmt.Println(d("  • Auth keys are NOT carried over — regenerate on destination"))
	fmt.Println()

	fmt.Println(h("  OTHER FLAGS"))
	fmt.Println()
	fmt.Printf("  %s  %s\n", m("--help    "), w("Show this help"))
	fmt.Printf("  %s  %s\n", m("--version "), w("Show version and machine fingerprint"))
	fmt.Printf("  %s  %s\n", m("--list    "), w("List connection names"))
	fmt.Printf("  %s  %s\n", m("--key-file"), w("Read auth key from file (safer than --key)"))
	fmt.Println()

	fmt.Println(h("  PROJECT"))
	fmt.Println()
	fmt.Printf("  %s  %s\n", m(padRight("Home:", 12)), c(repoURL))
	fmt.Printf("  %s  %s\n", m(padRight("Releases:", 12)), c(releasesURL))
	fmt.Printf("  %s  %s\n", m(padRight("Issues:", 12)), c(issuesURL))
	fmt.Printf("  %s  %s\n", m(padRight("License:", 12)), c(licenseName))
	fmt.Println()
	fmt.Printf("  SecureWrapper v%s  •  Built: %s  •  Machine: %s\n", version, buildDate, ShortFingerprint())
	fmt.Println()
}
